# Generated by Django 5.1.3 on 2025-01-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_with_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='bio',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='admin', max_length=12),
        ),
    ]
